[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "0.3.0" }
publishPlug = { id = "com.gradle.plugin-publish", version = "0.17.0" }
jacoco = { id = "pl.droidsonroids.jacoco.testkit", version = "1.0.12" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.1" }